### ISSUE TITLE
Android 24minApi

### ISSUE THREAD

**Issue by RationalEgoism** [snowe2010/pretty-print#33]
Add to the description that the library works correctly with 24minApi on Android, cause it uses java/util/Locale.Category
https://developer.android.com/reference/java/util/Locale.Category

`java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Locale$Category;
        at com.ibm.icu.util.ULocale$JDKLocaleHelper.getDefault(ULocale.java:4130)
        at com.ibm.icu.util.ULocale.<clinit>(ULocale.java:557)
        at com.ibm.icu.text.BreakIterator.getLineInstance(BreakIterator.java:638)
        at com.tylerthrailkill.helpers.prettyprint.PrettyPrinter.<init>(PrettyPrint.kt:50)
        at com.tylerthrailkill.helpers.prettyprint.PrettyPrintKt.pp(PrettyPrint.kt:21)
        at com.tylerthrailkill.helpers.prettyprint.PrettyPrintKt.pp$default(PrettyPrint.kt:20)`

**Comment by snowe2010** [comment]
>Add to the description that the library works correctly with 24minApi on Android, cause it uses java/util/Locale.Category

Works correctly? Or doesn't work correctly?
